# Generated by Django 5.1 on 2024-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('flood', 'Flood'), ('road_block', 'Road Blockage'), ('damage', 'Damage'), ('earthquake', 'Earthquake'), ('wildfire', 'Wildfire'), ('tornado', 'Tornado'), ('hurricane', 'Hurricane'), ('industrial_accident', 'Industrial Accident'), ('landslide', 'Landslide'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
