# Generated by Django 5.1.1 on 2024-09-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster_report',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disaster_report',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
